include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    #implicit-dynamic: false
  enable-experiment:
    - non-nullable
linter:
  rules:
    omit_local_variable_types: false
    prefer_single_quotes: false
    library_prefixes: false

