include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
linter:
  rules:
    omit_local_variable_types: false
    prefer_single_quotes: false
    library_prefixes: false